// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ChatMessage;
@class MessageHead;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MessageRoot : GPBRootObject
@end

#pragma mark - MessageHead

typedef GPB_ENUM(MessageHead_FieldNumber) {
  MessageHead_FieldNumber_From = 1,
  MessageHead_FieldNumber_To = 2,
  MessageHead_FieldNumber_MessageId = 3,
  MessageHead_FieldNumber_ChatType = 4,
  MessageHead_FieldNumber_Offline = 5,
};

/**
 * 消息 数据
 **/
@interface MessageHead : GPBMessage

/**
 * *
 * 发送者;
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *from;

/**
 * *
 * 接受者;
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

/**
 * *
 * 消息id
 *
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

/**
 * *
 * 聊天类型;(单聊,群聊)
 **/
@property(nonatomic, readwrite) int32_t chatType;

/**
 * *
 * 是否离线消息   true 离线消息
 **/
@property(nonatomic, readwrite) BOOL offline;

@end

#pragma mark - ChatMessage

typedef GPB_ENUM(ChatMessage_FieldNumber) {
  ChatMessage_FieldNumber_MessageHead = 1,
  ChatMessage_FieldNumber_FromUserId = 2,
  ChatMessage_FieldNumber_FromUserName = 3,
  ChatMessage_FieldNumber_ToUserId = 4,
  ChatMessage_FieldNumber_ToUserName = 5,
  ChatMessage_FieldNumber_TimeSend = 6,
  ChatMessage_FieldNumber_Type = 7,
  ChatMessage_FieldNumber_Content = 8,
  ChatMessage_FieldNumber_ObjectId = 9,
  ChatMessage_FieldNumber_FileName = 10,
  ChatMessage_FieldNumber_IsEncrypt = 11,
  ChatMessage_FieldNumber_DeleteTime = 12,
  ChatMessage_FieldNumber_IsReadDel = 13,
  ChatMessage_FieldNumber_FileSize = 14,
  ChatMessage_FieldNumber_FileTime = 15,
  ChatMessage_FieldNumber_LocationX = 16,
  ChatMessage_FieldNumber_LocationY = 17,
  ChatMessage_FieldNumber_EncryptType = 18,
  ChatMessage_FieldNumber_Signature = 19,
  ChatMessage_FieldNumber_Other = 20,
};

/**
 * 消息的 body
 **/
@interface ChatMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageHead *messageHead;
/** Test to see if @c messageHead has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHead;

/**
 * *
 * 业务发送者
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUserId;

/**
 * *
 * 发送者用户名
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUserName;

/**
 * *
 * 业务接受者
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *toUserId;

/**
 * *
 * 接受者用户名
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *toUserName;

/**
 * *
 *
 * 消息发送时间
 **/
@property(nonatomic, readwrite) int64_t timeSend;

/**
 * *
 * 消息类型;
 **/
@property(nonatomic, readwrite) int32_t type;

/**
 * *
 * 消息内容;
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/**
 * *
 * 消息发到哪个群组;
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *objectId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileName;

/** 是否加密传输 */
@property(nonatomic, readwrite) BOOL isEncrypt;

@property(nonatomic, readwrite) int64_t deleteTime;

/** 是否阅后即焚 */
@property(nonatomic, readwrite) BOOL isReadDel;

/**  文件大小 单位字节 */
@property(nonatomic, readwrite) int64_t fileSize;

/** 文件播放时长  录音时长，视频时长 */
@property(nonatomic, readwrite) int64_t fileTime;

/** 1.当为地理位置时，有效 2.特殊：当为图片时，该值为图片的宽度 */
@property(nonatomic, readwrite) double locationX;

/** 1.当为地理位置时，有效 2.特殊：当为图片时，该值为图片的高度 */
@property(nonatomic, readwrite) double locationY;

/**
 * *
 * 加密类型;
 **/
@property(nonatomic, readwrite) int32_t encryptType;

/**
 *
 * 消息验签字段
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

/**
 *
 * 907 传递信息
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *other;

@end

#pragma mark - AuthMessage

typedef GPB_ENUM(AuthMessage_FieldNumber) {
  AuthMessage_FieldNumber_MessageHead = 1,
  AuthMessage_FieldNumber_Token = 2,
  AuthMessage_FieldNumber_Password = 3,
  AuthMessage_FieldNumber_DeviceId = 4,
};

/**
 * *
 * 登陆授权消息
 **/
@interface AuthMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageHead *messageHead;
/** Test to see if @c messageHead has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHead;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@end

#pragma mark - AuthRespMessageProBuf

typedef GPB_ENUM(AuthRespMessageProBuf_FieldNumber) {
  AuthRespMessageProBuf_FieldNumber_MessageHead = 1,
  AuthRespMessageProBuf_FieldNumber_Status = 2,
  AuthRespMessageProBuf_FieldNumber_Arg = 3,
  AuthRespMessageProBuf_FieldNumber_Token = 4,
  AuthRespMessageProBuf_FieldNumber_Resources = 5,
};

/**
 * *
 * 登陆授权消息结果
 **/
@interface AuthRespMessageProBuf : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageHead *messageHead;
/** Test to see if @c messageHead has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHead;

/**
 * *
 * 登陆结果  1 登陆 成功     0 登陆失败
 **/
@property(nonatomic, readwrite) int32_t status;

/**
 *
 * 提示信息
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *arg;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resources;

@end

#pragma mark - MessageReceiptStatusProBuf

typedef GPB_ENUM(MessageReceiptStatusProBuf_FieldNumber) {
  MessageReceiptStatusProBuf_FieldNumber_MessageHead = 1,
  MessageReceiptStatusProBuf_FieldNumber_Status = 2,
  MessageReceiptStatusProBuf_FieldNumber_MessageId = 3,
};

/**
 * *
 * 消息回执
 **/
@interface MessageReceiptStatusProBuf : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageHead *messageHead;
/** Test to see if @c messageHead has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHead;

/**
 * *
 *   0  发送中     1  到达服务器
 *    2 已接收   3 已读
 **/
@property(nonatomic, readwrite) int32_t status;

/**
 *
 * 提示信息
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

@end

#pragma mark - JoinGroupMessageProBuf

typedef GPB_ENUM(JoinGroupMessageProBuf_FieldNumber) {
  JoinGroupMessageProBuf_FieldNumber_MessageHead = 1,
  JoinGroupMessageProBuf_FieldNumber_Jid = 2,
  JoinGroupMessageProBuf_FieldNumber_Seconds = 3,
};

/**
 * *
 * 加入群组消息
 **/
@interface JoinGroupMessageProBuf : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageHead *messageHead;
/** Test to see if @c messageHead has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHead;

@property(nonatomic, readwrite, copy, null_resettable) NSString *jid;

@property(nonatomic, readwrite) int64_t seconds;

@end

#pragma mark - ExitGroupMessageProBuf

typedef GPB_ENUM(ExitGroupMessageProBuf_FieldNumber) {
  ExitGroupMessageProBuf_FieldNumber_MessageHead = 1,
  ExitGroupMessageProBuf_FieldNumber_Jid = 2,
};

@interface ExitGroupMessageProBuf : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageHead *messageHead;
/** Test to see if @c messageHead has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHead;

@property(nonatomic, readwrite, copy, null_resettable) NSString *jid;

@end

#pragma mark - GroupMessageRespProBuf

typedef GPB_ENUM(GroupMessageRespProBuf_FieldNumber) {
  GroupMessageRespProBuf_FieldNumber_MessageHead = 1,
  GroupMessageRespProBuf_FieldNumber_Jid = 2,
  GroupMessageRespProBuf_FieldNumber_Status = 3,
  GroupMessageRespProBuf_FieldNumber_IsExit = 4,
};

/**
 * *
 * 群组协议结果
 **/
@interface GroupMessageRespProBuf : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageHead *messageHead;
/** Test to see if @c messageHead has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHead;

@property(nonatomic, readwrite, copy, null_resettable) NSString *jid;

/**
 * *
 * 1     成功
 * -1  失败
 **/
@property(nonatomic, readwrite) int32_t status;

/**
 * *
 * 是否退出群组协议
 **/
@property(nonatomic, readwrite) BOOL isExit;

@end

#pragma mark - PullMessageHistoryRecordReqProBuf

typedef GPB_ENUM(PullMessageHistoryRecordReqProBuf_FieldNumber) {
  PullMessageHistoryRecordReqProBuf_FieldNumber_MessageHead = 1,
  PullMessageHistoryRecordReqProBuf_FieldNumber_Jid = 2,
  PullMessageHistoryRecordReqProBuf_FieldNumber_Size = 3,
  PullMessageHistoryRecordReqProBuf_FieldNumber_StartTime = 4,
  PullMessageHistoryRecordReqProBuf_FieldNumber_EndTime = 5,
};

/**
 * *
 * 漫游聊天记录
 **/
@interface PullMessageHistoryRecordReqProBuf : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageHead *messageHead;
/** Test to see if @c messageHead has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHead;

@property(nonatomic, readwrite, copy, null_resettable) NSString *jid;

/**
 * *
 * 请求数量
 **/
@property(nonatomic, readwrite) int32_t size;

/**
 * *
 * 开始时间
 **/
@property(nonatomic, readwrite) int64_t startTime;

/**
 * *
 * 结束时间
 **/
@property(nonatomic, readwrite) int64_t endTime;

@end

#pragma mark - PullMessageHistoryRecordRespProBuf

typedef GPB_ENUM(PullMessageHistoryRecordRespProBuf_FieldNumber) {
  PullMessageHistoryRecordRespProBuf_FieldNumber_MessageId = 1,
  PullMessageHistoryRecordRespProBuf_FieldNumber_Jid = 2,
  PullMessageHistoryRecordRespProBuf_FieldNumber_ChatType = 3,
  PullMessageHistoryRecordRespProBuf_FieldNumber_MessageListArray = 4,
  PullMessageHistoryRecordRespProBuf_FieldNumber_Count = 5,
};

/**
 * *
 * 漫游聊天记录  结果
 **/
@interface PullMessageHistoryRecordRespProBuf : GPBMessage

/**
 * *
 * 请求ID 标识
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *jid;

/**
 * *
 *
 **/
@property(nonatomic, readwrite) int32_t chatType;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ChatMessage*> *messageListArray;
/** The number of items in @c messageListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messageListArray_Count;

/**
 * *
 * 消息总数
 **/
@property(nonatomic, readwrite) int32_t count;

@end

#pragma mark - PullBatchGroupMessageReqProBuf

typedef GPB_ENUM(PullBatchGroupMessageReqProBuf_FieldNumber) {
  PullBatchGroupMessageReqProBuf_FieldNumber_MessageHead = 1,
  PullBatchGroupMessageReqProBuf_FieldNumber_JidListArray = 2,
  PullBatchGroupMessageReqProBuf_FieldNumber_EndTime = 3,
};

/**
 * *
 * 批量拉取群组消息数量
 **/
@interface PullBatchGroupMessageReqProBuf : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageHead *messageHead;
/** Test to see if @c messageHead has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHead;

/**
 * *
 * jid 群组jid   lastTime 群组的最后一条消息时间
 * 群组数据集合["jid1,lastTime","jid2,lastTime"]
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *jidListArray;
/** The number of items in @c jidListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger jidListArray_Count;

/**
 * *
 * 拉取消息的截止时间
 **/
@property(nonatomic, readwrite) int64_t endTime;

@end

#pragma mark - PullGroupMessageRespProBuf

typedef GPB_ENUM(PullGroupMessageRespProBuf_FieldNumber) {
  PullGroupMessageRespProBuf_FieldNumber_MessageId = 1,
  PullGroupMessageRespProBuf_FieldNumber_Jid = 2,
  PullGroupMessageRespProBuf_FieldNumber_Count = 3,
  PullGroupMessageRespProBuf_FieldNumber_MessageListArray = 4,
};

/**
 * *
 * 批量拉取群组消息数量   及最后几条消息  结果   (单个群组的)
 **/
@interface PullGroupMessageRespProBuf : GPBMessage

/**
 * *
 * 请求ID 标识
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

/**
 * *
 * 群组jid
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *jid;

/**
 * *
 * 群组消息数量
 **/
@property(nonatomic, readwrite) int64_t count;

/**
 * *
 * 消息集合
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ChatMessage*> *messageListArray;
/** The number of items in @c messageListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messageListArray_Count;

@end

#pragma mark - PingMessageProBuf

typedef GPB_ENUM(PingMessageProBuf_FieldNumber) {
  PingMessageProBuf_FieldNumber_MessageHead = 1,
};

/**
 * 心跳协议
 **/
@interface PingMessageProBuf : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageHead *messageHead;
/** Test to see if @c messageHead has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHead;

@end

#pragma mark - CommonSuccessProBuf

typedef GPB_ENUM(CommonSuccessProBuf_FieldNumber) {
  CommonSuccessProBuf_FieldNumber_MessageHead = 1,
};

@interface CommonSuccessProBuf : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageHead *messageHead;
/** Test to see if @c messageHead has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHead;

@end

#pragma mark - CommonErrorProBuf

typedef GPB_ENUM(CommonErrorProBuf_FieldNumber) {
  CommonErrorProBuf_FieldNumber_MessageHead = 1,
  CommonErrorProBuf_FieldNumber_Code = 2,
  CommonErrorProBuf_FieldNumber_Arg = 3,
};

/**
 * 错误协议
 **/
@interface CommonErrorProBuf : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageHead *messageHead;
/** Test to see if @c messageHead has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHead;

@property(nonatomic, readwrite) int32_t code;

/** 错误参数，格式：xx,xxx,xxxx */
@property(nonatomic, readwrite, copy, null_resettable) NSString *arg;

@end

#pragma mark - ServerReqMessageProBuf

typedef GPB_ENUM(ServerReqMessageProBuf_FieldNumber) {
  ServerReqMessageProBuf_FieldNumber_Type = 1,
  ServerReqMessageProBuf_FieldNumber_Content = 2,
};

@interface ServerReqMessageProBuf : GPBMessage

/** 服务器消息类型 */
@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
