// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: br.proto

#include "br.pb.h"
#include "br.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace pb {

static const char* LotteryQuery_method_names[] = {
  "/pb.LotteryQuery/FetchLotteryInfo",
};

std::unique_ptr< LotteryQuery::Stub> LotteryQuery::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LotteryQuery::Stub> stub(new LotteryQuery::Stub(channel, options));
  return stub;
}

LotteryQuery::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_FetchLotteryInfo_(LotteryQuery_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LotteryQuery::Stub::FetchLotteryInfo(::grpc::ClientContext* context, const ::pb::LotteryRequest& request, ::pb::LotteryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::pb::LotteryRequest, ::pb::LotteryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FetchLotteryInfo_, context, request, response);
}

void LotteryQuery::Stub::async::FetchLotteryInfo(::grpc::ClientContext* context, const ::pb::LotteryRequest* request, ::pb::LotteryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::pb::LotteryRequest, ::pb::LotteryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FetchLotteryInfo_, context, request, response, std::move(f));
}

void LotteryQuery::Stub::async::FetchLotteryInfo(::grpc::ClientContext* context, const ::pb::LotteryRequest* request, ::pb::LotteryResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FetchLotteryInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pb::LotteryResponse>* LotteryQuery::Stub::PrepareAsyncFetchLotteryInfoRaw(::grpc::ClientContext* context, const ::pb::LotteryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pb::LotteryResponse, ::pb::LotteryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FetchLotteryInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pb::LotteryResponse>* LotteryQuery::Stub::AsyncFetchLotteryInfoRaw(::grpc::ClientContext* context, const ::pb::LotteryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFetchLotteryInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

LotteryQuery::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LotteryQuery_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LotteryQuery::Service, ::pb::LotteryRequest, ::pb::LotteryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LotteryQuery::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pb::LotteryRequest* req,
             ::pb::LotteryResponse* resp) {
               return service->FetchLotteryInfo(ctx, req, resp);
             }, this)));
}

LotteryQuery::Service::~Service() {
}

::grpc::Status LotteryQuery::Service::FetchLotteryInfo(::grpc::ServerContext* context, const ::pb::LotteryRequest* request, ::pb::LotteryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace pb

