// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: br.proto
#ifndef GRPC_br_2eproto__INCLUDED
#define GRPC_br_2eproto__INCLUDED

#include "br.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace pb {

// Lottery服务service定义
class LotteryQuery final {
 public:
  static constexpr char const* service_full_name() {
    return "pb.LotteryQuery";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status FetchLotteryInfo(::grpc::ClientContext* context, const ::pb::LotteryRequest& request, ::pb::LotteryResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pb::LotteryResponse>> AsyncFetchLotteryInfo(::grpc::ClientContext* context, const ::pb::LotteryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pb::LotteryResponse>>(AsyncFetchLotteryInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pb::LotteryResponse>> PrepareAsyncFetchLotteryInfo(::grpc::ClientContext* context, const ::pb::LotteryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pb::LotteryResponse>>(PrepareAsyncFetchLotteryInfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void FetchLotteryInfo(::grpc::ClientContext* context, const ::pb::LotteryRequest* request, ::pb::LotteryResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FetchLotteryInfo(::grpc::ClientContext* context, const ::pb::LotteryRequest* request, ::pb::LotteryResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pb::LotteryResponse>* AsyncFetchLotteryInfoRaw(::grpc::ClientContext* context, const ::pb::LotteryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pb::LotteryResponse>* PrepareAsyncFetchLotteryInfoRaw(::grpc::ClientContext* context, const ::pb::LotteryRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status FetchLotteryInfo(::grpc::ClientContext* context, const ::pb::LotteryRequest& request, ::pb::LotteryResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pb::LotteryResponse>> AsyncFetchLotteryInfo(::grpc::ClientContext* context, const ::pb::LotteryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pb::LotteryResponse>>(AsyncFetchLotteryInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pb::LotteryResponse>> PrepareAsyncFetchLotteryInfo(::grpc::ClientContext* context, const ::pb::LotteryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pb::LotteryResponse>>(PrepareAsyncFetchLotteryInfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void FetchLotteryInfo(::grpc::ClientContext* context, const ::pb::LotteryRequest* request, ::pb::LotteryResponse* response, std::function<void(::grpc::Status)>) override;
      void FetchLotteryInfo(::grpc::ClientContext* context, const ::pb::LotteryRequest* request, ::pb::LotteryResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::pb::LotteryResponse>* AsyncFetchLotteryInfoRaw(::grpc::ClientContext* context, const ::pb::LotteryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pb::LotteryResponse>* PrepareAsyncFetchLotteryInfoRaw(::grpc::ClientContext* context, const ::pb::LotteryRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_FetchLotteryInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status FetchLotteryInfo(::grpc::ServerContext* context, const ::pb::LotteryRequest* request, ::pb::LotteryResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_FetchLotteryInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FetchLotteryInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_FetchLotteryInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchLotteryInfo(::grpc::ServerContext* /*context*/, const ::pb::LotteryRequest* /*request*/, ::pb::LotteryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchLotteryInfo(::grpc::ServerContext* context, ::pb::LotteryRequest* request, ::grpc::ServerAsyncResponseWriter< ::pb::LotteryResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_FetchLotteryInfo<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_FetchLotteryInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FetchLotteryInfo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::pb::LotteryRequest, ::pb::LotteryResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pb::LotteryRequest* request, ::pb::LotteryResponse* response) { return this->FetchLotteryInfo(context, request, response); }));}
    void SetMessageAllocatorFor_FetchLotteryInfo(
        ::grpc::MessageAllocator< ::pb::LotteryRequest, ::pb::LotteryResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pb::LotteryRequest, ::pb::LotteryResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FetchLotteryInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchLotteryInfo(::grpc::ServerContext* /*context*/, const ::pb::LotteryRequest* /*request*/, ::pb::LotteryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FetchLotteryInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::pb::LotteryRequest* /*request*/, ::pb::LotteryResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_FetchLotteryInfo<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_FetchLotteryInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FetchLotteryInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_FetchLotteryInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchLotteryInfo(::grpc::ServerContext* /*context*/, const ::pb::LotteryRequest* /*request*/, ::pb::LotteryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_FetchLotteryInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FetchLotteryInfo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_FetchLotteryInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchLotteryInfo(::grpc::ServerContext* /*context*/, const ::pb::LotteryRequest* /*request*/, ::pb::LotteryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchLotteryInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FetchLotteryInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FetchLotteryInfo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FetchLotteryInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_FetchLotteryInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchLotteryInfo(::grpc::ServerContext* /*context*/, const ::pb::LotteryRequest* /*request*/, ::pb::LotteryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FetchLotteryInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FetchLotteryInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FetchLotteryInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pb::LotteryRequest, ::pb::LotteryResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pb::LotteryRequest, ::pb::LotteryResponse>* streamer) {
                       return this->StreamedFetchLotteryInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FetchLotteryInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FetchLotteryInfo(::grpc::ServerContext* /*context*/, const ::pb::LotteryRequest* /*request*/, ::pb::LotteryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFetchLotteryInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pb::LotteryRequest,::pb::LotteryResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_FetchLotteryInfo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_FetchLotteryInfo<Service > StreamedService;
};

}  // namespace pb


#endif  // GRPC_br_2eproto__INCLUDED
